/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fatec.poo.view;

import fatec.poo.model.Cliente;
import fatec.poo.model.ItemPedido;
import fatec.poo.model.Pedido;
import fatec.poo.model.Pessoa;
import fatec.poo.model.Produto;
import fatec.poo.model.Vendedor;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JULIOAUGUSTORIBEIROD
 */
public class GuiEmitirPedido extends javax.swing.JFrame {

    /**
     * Creates new form GuiEmitirPedido
     */
    public GuiEmitirPedido(ArrayList<Pedido> ped, ArrayList<Pessoa> cliVend, ArrayList<Produto> prod) {
        initComponents();
        cadPedido = ped;
        cadCliVend = cliVend;
        cadProd = prod;
        modTblProd = (DefaultTableModel) tblProduto.getModel();
        txtNumPedido.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgrFormaDePagamento = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNumPedido = new javax.swing.JTextField();
        btnConsultarPedido = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtDataPedido = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        rbtAVista = new javax.swing.JRadioButton();
        rbtAPrazo = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtCPFCliente = new javax.swing.JFormattedTextField();
        btnConsultarCliente = new javax.swing.JButton();
        lblNomeCliente = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtCPFVendedor = new javax.swing.JFormattedTextField();
        btnConsultarVendedor = new javax.swing.JButton();
        lblNomeVendedor = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        btnConsultarProduto = new javax.swing.JButton();
        lblDescricaoProduto = new javax.swing.JLabel();
        txtCodProduto = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtQtdeVendida = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblValorTotalPed = new javax.swing.JLabel();
        lblQtdeItensPed = new javax.swing.JLabel();
        btnRemoverItem = new javax.swing.JButton();
        btnAdicionarItem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProduto = new javax.swing.JTable();
        btnSair = new javax.swing.JButton();
        btnIncluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Emitir Pedido");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Pedido"));

        jLabel1.setText("Número do Pedido");

        btnConsultarPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/pesq.png"))); // NOI18N
        btnConsultarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarPedidoActionPerformed(evt);
            }
        });

        jLabel2.setText("Data do Pedido");

        try {
            txtDataPedido.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataPedido.setEnabled(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Forma de Pagamento"));

        btgrFormaDePagamento.add(rbtAVista);
        rbtAVista.setSelected(true);
        rbtAVista.setText("A vista");
        rbtAVista.setEnabled(false);

        btgrFormaDePagamento.add(rbtAPrazo);
        rbtAPrazo.setText("A prazo");
        rbtAPrazo.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbtAVista)
                .addGap(18, 18, 18)
                .addComponent(rbtAPrazo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtAVista)
                    .addComponent(rbtAPrazo))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNumPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConsultarPedido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDataPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtDataPedido, txtNumPedido});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNumPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultarPedido)
                    .addComponent(jLabel2)
                    .addComponent(txtDataPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Cliente"));

        jLabel3.setText("CPF Cliente");

        try {
            txtCPFCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCPFCliente.setEnabled(false);

        btnConsultarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/pesq.png"))); // NOI18N
        btnConsultarCliente.setEnabled(false);
        btnConsultarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarClienteActionPerformed(evt);
            }
        });

        lblNomeCliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCPFCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConsultarCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNomeCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnConsultarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtCPFCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblNomeCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Vendedor"));

        jLabel5.setText("CPF Vendedor");

        try {
            txtCPFVendedor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCPFVendedor.setEnabled(false);

        btnConsultarVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/pesq.png"))); // NOI18N
        btnConsultarVendedor.setEnabled(false);
        btnConsultarVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarVendedorActionPerformed(evt);
            }
        });

        lblNomeVendedor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCPFVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConsultarVendedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNomeVendedor, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnConsultarVendedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(txtCPFVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblNomeVendedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Itens do Pedido"));

        jLabel9.setText("Código do Produto");

        btnConsultarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/pesq.png"))); // NOI18N
        btnConsultarProduto.setEnabled(false);
        btnConsultarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarProdutoActionPerformed(evt);
            }
        });

        lblDescricaoProduto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        txtCodProduto.setEnabled(false);

        jLabel11.setText("Qtde Vendida");

        txtQtdeVendida.setEnabled(false);

        jLabel12.setText("Valor Total do Pedido");

        jLabel13.setText("Quantidade de Itens Pedidos");

        lblValorTotalPed.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        lblQtdeItensPed.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        btnRemoverItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/rem.png"))); // NOI18N
        btnRemoverItem.setText("Remover Item");
        btnRemoverItem.setEnabled(false);
        btnRemoverItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverItemActionPerformed(evt);
            }
        });

        btnAdicionarItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/add.png"))); // NOI18N
        btnAdicionarItem.setText("Adicionar Item");
        btnAdicionarItem.setEnabled(false);
        btnAdicionarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarItemActionPerformed(evt);
            }
        });

        tblProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descrição", "Prec. Unit.", "Qtde. Vend.", "SubTotal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblProduto);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblValorTotalPed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblQtdeItensPed, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnConsultarProduto)
                        .addGap(6, 6, 6)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(btnAdicionarItem)
                                .addGap(30, 30, 30)
                                .addComponent(btnRemoverItem))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(lblDescricaoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtQtdeVendida, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(txtQtdeVendida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblDescricaoProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addComponent(txtCodProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnConsultarProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRemoverItem)
                    .addComponent(btnAdicionarItem))
                .addGap(13, 13, 13)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(lblValorTotalPed, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(lblQtdeItensPed, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblQtdeItensPed, lblValorTotalPed});

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/exit.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/add.png"))); // NOI18N
        btnIncluir.setText("Incluir");
        btnIncluir.setEnabled(false);
        btnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirActionPerformed(evt);
            }
        });

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Alterar.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setEnabled(false);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Eraser.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnIncluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSair)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAlterar, btnExcluir, btnIncluir, btnSair});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jPanel1, jPanel3, jPanel4, jPanel6});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSair)
                    .addComponent(btnIncluir)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarPedidoActionPerformed
        DecimalFormat formato  = new DecimalFormat("#,##0.00");
        if (!txtNumPedido.getText().matches("[0-9]+")) {
            JOptionPane.showMessageDialog(null, 
                    "Número de Pedido inválido!", 
                    "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int i;
        for (i=0; i<cadPedido.size(); i++) {
            if (cadPedido.get(i).getNumero().equals(txtNumPedido.getText())) {
                break;
            }
        }
        if (i < cadPedido.size()) {
            posPedido = i;
        }
        else {
            posPedido = -1;
        }
        
        if (posPedido >= 0) {
            pedido = (Pedido)cadPedido.get(posPedido);
            txtCPFCliente.setText(pedido.getCliente().getCpf());
            lblNomeCliente.setText(pedido.getCliente().getNome());
            txtCPFVendedor.setText(pedido.getVendedor().getCpf());
            lblNomeVendedor.setText(pedido.getVendedor().getNome());
            txtDataPedido.setText(pedido.getDataEmissao());
            if(pedido.isFormaPagto())
                rbtAVista.setSelected(true);
            else
                rbtAPrazo.setSelected(true);
            lblValorTotalPed.setText(String.valueOf(pedido.calcValorTotal()));
            lblQtdeItensPed.setText(String.valueOf(pedido.getItensPedido().size()));
            
            txtCodProduto.setEnabled(true);
            btnConsultarProduto.setEnabled(true);
            btnRemoverItem.setEnabled(true);
            btnIncluir.setEnabled(false);
            btnAlterar.setEnabled(true);
            btnExcluir.setEnabled(true);
            
            seqItemPed = pedido.getItensPedido()
                    .get(pedido.getItensPedido().size()-1).getSequencia() + 1;
            itensPedidoAntesAlterar = new ArrayList<ItemPedido>();
            for(i=0;i<pedido.getItensPedido().size();i++){
                String linha[] = {
                    pedido.getItensPedido().get(i).getProduto().getCodigo(),
                    pedido.getItensPedido().get(i).getProduto().getDescricao(),
                    formato.format(pedido.getItensPedido().get(i).getProduto().getPreco()),
                    formato.format(pedido.getItensPedido().get(i).getQtdeVendida()),
                    formato.format(pedido.getItensPedido().get(i).calcValor())
                };
                modTblProd.addRow(linha);
                
                itensPedidoAntesAlterar.add(new ItemPedido(pedido.getItensPedido().get(i)));
            }
        }
        else {
            seqItemPed = 0;
            txtDataPedido.setEnabled(true);
            rbtAPrazo.setEnabled(true);
            rbtAVista.setEnabled(true);
            txtCPFCliente.setEnabled(true);
            btnConsultarCliente.setEnabled(true);
        }
            
        btnConsultarPedido.setEnabled(false);
    }//GEN-LAST:event_btnConsultarPedidoActionPerformed

    private void btnConsultarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarClienteActionPerformed
        Date data = null;
        String dataTexto = txtDataPedido.getText();
        SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
        try {
            format.setLenient(false);
            data = format.parse(dataTexto);
            pedido = new Pedido(txtNumPedido.getText(),txtDataPedido.getText());
            pedido.setFormaPagto(rbtAVista.isSelected());
            txtDataPedido.setEnabled(false);
            btnConsultarCliente.setEnabled(true);
            txtCPFCliente.setEnabled(true);   
            txtNumPedido.setEnabled(false);
            rbtAPrazo.setEnabled(false);
            rbtAVista.setEnabled(false);
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(null, "Data Inválida", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int i;
        for (i=0; i<cadCliVend.size(); i++) {
            if (cadCliVend.get(i) instanceof Cliente) {
                if (cadCliVend.get(i).getCpf().equals(txtCPFCliente.getText())) {
                    break;
                }
            }
        }
        if(i>=cadCliVend.size()){
            JOptionPane.showMessageDialog(null, "Cliente não encontrado", "Aviso", JOptionPane.WARNING_MESSAGE);
                }
        else{
            pedido.setCliente((Cliente)cadCliVend.get(i));
            (cadCliVend.get(i)).addPedido(pedido);
            lblNomeCliente.setText(cadCliVend.get(i).getNome());
            btnConsultarCliente.setEnabled(false);
            txtCPFCliente.setEnabled(false);
            btnConsultarVendedor.setEnabled(true);
            txtCPFVendedor.setEnabled(true);
            txtCPFVendedor.requestFocus();
        }
    }//GEN-LAST:event_btnConsultarClienteActionPerformed

    private void btnConsultarVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarVendedorActionPerformed
        int i;
        for (i=0; i<cadCliVend.size(); i++) {
            if (cadCliVend.get(i) instanceof Vendedor) {
                if (cadCliVend.get(i).getCpf().equals(txtCPFVendedor.getText())) {
                    break;
                }
            }
        }
        if(i>=cadCliVend.size()){
            JOptionPane.showMessageDialog(null, "Vendedor não encontrado", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
        else{
            pedido.setVendedor((Vendedor)cadCliVend.get(i));
            cadCliVend.get(i).addPedido(pedido);
            lblNomeVendedor.setText(cadCliVend.get(i).getNome());
            btnConsultarVendedor.setEnabled(false);
            txtCPFVendedor.setEnabled(false);
            txtCodProduto.setEnabled(true);
            btnConsultarProduto.setEnabled(true);
            btnIncluir.setEnabled(true);
            txtCodProduto.requestFocus();
        }
    }//GEN-LAST:event_btnConsultarVendedorActionPerformed

    private void btnConsultarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarProdutoActionPerformed
        int x;
        for (x = 0; x < cadProd.size(); x++){ 
            if (cadProd.get(x).getCodigo().equals(txtCodProduto.getText())){
                break;
            }
        } 

        if (x < cadProd.size()){
           posProd = x;
        }else{
           posProd = -1;
        }
        
        if (posProd >= 0) {
            lblDescricaoProduto.setText(cadProd.get(posProd).getDescricao());
            txtQtdeVendida.setEnabled(true);
            btnAdicionarItem.setEnabled(true);
            txtQtdeVendida.requestFocus();
        }
        else {
            JOptionPane.showMessageDialog(null, "Produto não encontrado!", 
                    "Aviso", JOptionPane.WARNING_MESSAGE);
            
            txtCodProduto.setText(null);
            lblDescricaoProduto.setText(null);
            txtQtdeVendida.setText(null);
            txtQtdeVendida.setEnabled(false);
            btnAdicionarItem.setEnabled(false);
            if (modTblProd.getRowCount() == 0)
                btnRemoverItem.setEnabled(false);
            txtCodProduto.requestFocus();
        }
    }//GEN-LAST:event_btnConsultarProdutoActionPerformed

    private void btnAdicionarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarItemActionPerformed
        DecimalFormat formato  = new DecimalFormat("#,##0.00");
        if (txtQtdeVendida.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, 
                    "Quantidade vendida deve ser maior que zero!", 
                    "Aviso", JOptionPane.WARNING_MESSAGE);
            txtQtdeVendida.setText(null);
            txtQtdeVendida.requestFocus();
            return;
        }
        double qtdeVendida = Double.parseDouble(txtQtdeVendida.getText());
        if (qtdeVendida <= 0) {
            JOptionPane.showMessageDialog(null, 
                    "Quantidade vendida deve ser maior que zero!", 
                    "Aviso", JOptionPane.WARNING_MESSAGE);
            txtQtdeVendida.setText(null);
            txtQtdeVendida.requestFocus();
            return;
        }
        
        Produto produto = cadProd.get(posProd);
        if (qtdeVendida > produto.getQtdeEstoque()) {
            JOptionPane.showMessageDialog(null, 
                    "Quantidade em estoque menor que a quantidade a ser vendida!" +
                    "\nEstoque: " + produto.getQtdeEstoque() +
                    "\nQuantidade a ser vendida: " + qtdeVendida, 
                    "Aviso", JOptionPane.WARNING_MESSAGE);
            txtQtdeVendida.setText(null);
            txtQtdeVendida.requestFocus();
            return;
        }
        
        ItemPedido itemPedido = new ItemPedido(seqItemPed, qtdeVendida, produto);
        if (itemPedido.calcValor() > pedido.getCliente().getLimiteDisp()) {
            JOptionPane.showMessageDialog(null, 
                    "Cliente não tem limite disponível o suficiente" +
                    "para adicionar esta quantidade deste produto!" +
                    "\nLimite disponível: " + pedido.getCliente().getLimiteDisp() +
                    "\nValor: " + itemPedido.calcValor(), 
                    "Aviso", JOptionPane.WARNING_MESSAGE);
            itemPedido.setQtdeVendida(0);
            txtQtdeVendida.setText(null);
            txtQtdeVendida.requestFocus();
            return;
        }
        
        pedido.addItemPedido(itemPedido);
        seqItemPed++;
               
        String linha[] = {
            produto.getCodigo(),
            produto.getDescricao(),
            formato.format(produto.getPreco()),
            formato.format(itemPedido.getQtdeVendida()),
            formato.format(itemPedido.calcValor())
        };
        modTblProd.addRow(linha);
        
        lblQtdeItensPed.setText(String.valueOf(modTblProd.getRowCount()));
        lblValorTotalPed.setText(formato.format(pedido.calcValorTotal()));
        
        btnRemoverItem.setEnabled(true);
    }//GEN-LAST:event_btnAdicionarItemActionPerformed

    private void btnRemoverItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverItemActionPerformed
        DecimalFormat formato  = new DecimalFormat("#,##0.00");
        if (tblProduto.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "A linha não foi selecionada", 
                    "Aviso", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        pedido.removeItemPedido(tblProduto.getSelectedRow());
        modTblProd.removeRow(tblProduto.getSelectedRow());
        
        lblValorTotalPed.setText(formato.format(pedido.calcValorTotal()));
        lblQtdeItensPed.setText(String.valueOf(modTblProd.getRowCount()));
        
        if (modTblProd.getRowCount() == 0)
                btnRemoverItem.setEnabled(false);
    }//GEN-LAST:event_btnRemoverItemActionPerformed

    private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirActionPerformed
        cadPedido.add(pedido);
        posPedido = -1;
        pedido = null;
        ativarModoConsulta();
    }//GEN-LAST:event_btnIncluirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        itensPedidoAntesAlterar = null;
        posPedido = -1;
        pedido = null;
        ativarModoConsulta();
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int i;
        for (i=0; i<pedido.getCliente().getPedidos().size(); i++) {
            if (pedido.getCliente().getPedidos().get(i).getNumero().equals(pedido.getNumero())) {
                pedido.getCliente().getPedidos().remove(i);
                break;
            }
        }
        for (i=0; i<pedido.getVendedor().getPedidos().size(); i++) {
            if (pedido.getVendedor().getPedidos().get(i).getNumero().equals(pedido.getNumero())) {
                pedido.getVendedor().getPedidos().remove(i);
                break;
            }
        }
        for (i=pedido.getItensPedido().size()-1; i>=0; i--) {
            pedido.removeItemPedido(i);
        }
        cadPedido.remove(posPedido);
        itensPedidoAntesAlterar = null;
        posPedido = -1;
        pedido = null;
        ativarModoConsulta();
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        int i;
        if (posPedido == -1 && pedido != null) {
            if (pedido.getCliente() != null) {
                for (i=0; i<pedido.getCliente().getPedidos().size(); i++) {
                    if (pedido.getCliente().getPedidos().get(i).getNumero().equals(pedido.getNumero())) {
                        pedido.getCliente().getPedidos().remove(i);
                        break;
                    }
                }
            }
            if (pedido.getVendedor() != null) {
                for (i=0; i<pedido.getVendedor().getPedidos().size(); i++) {
                if (pedido.getVendedor().getPedidos().get(i).getNumero().equals(pedido.getNumero())) {
                        pedido.getVendedor().getPedidos().remove(i);
                        break;
                    }
                }
            }
            for (i=0; i<pedido.getItensPedido().size(); i++) {
                pedido.removeItemPedido(i);
            }
        }
        else if (pedido != null) {
            for (i=pedido.getItensPedido().size()-1; i>=0; i--) {
                pedido.removeItemPedido(i);
            }
            
            for (i=0; i<itensPedidoAntesAlterar.size(); i++) {
                pedido.addItemPedido(
                        new ItemPedido(
                                itensPedidoAntesAlterar.get(i).getSequencia(),
                                itensPedidoAntesAlterar.get(i).getQtdeVendida(),
                                itensPedidoAntesAlterar.get(i).getProduto()
                        )
                );
            }
        }
        
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgrFormaDePagamento;
    private javax.swing.JButton btnAdicionarItem;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnConsultarCliente;
    private javax.swing.JButton btnConsultarPedido;
    private javax.swing.JButton btnConsultarProduto;
    private javax.swing.JButton btnConsultarVendedor;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnIncluir;
    private javax.swing.JButton btnRemoverItem;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDescricaoProduto;
    private javax.swing.JLabel lblNomeCliente;
    private javax.swing.JLabel lblNomeVendedor;
    private javax.swing.JLabel lblQtdeItensPed;
    private javax.swing.JLabel lblValorTotalPed;
    private javax.swing.JRadioButton rbtAPrazo;
    private javax.swing.JRadioButton rbtAVista;
    private javax.swing.JTable tblProduto;
    private javax.swing.JFormattedTextField txtCPFCliente;
    private javax.swing.JFormattedTextField txtCPFVendedor;
    private javax.swing.JTextField txtCodProduto;
    private javax.swing.JFormattedTextField txtDataPedido;
    private javax.swing.JTextField txtNumPedido;
    private javax.swing.JTextField txtQtdeVendida;
    // End of variables declaration//GEN-END:variables
    private ArrayList<Pedido> cadPedido;
    private ArrayList<Pessoa> cadCliVend;
    private ArrayList<Produto> cadProd;
    private int posPedido = -1, posProd;
    private Pedido pedido;
    private int seqItemPed = 1;
    private DefaultTableModel modTblProd;
    private ArrayList<ItemPedido> itensPedidoAntesAlterar;
    
    private void ativarModoConsulta() {
        txtNumPedido.setText(null);
        txtDataPedido.setText(null);
        rbtAVista.setSelected(true);
        txtCPFCliente.setText(null);
        lblNomeCliente.setText(null);
        txtCPFVendedor.setText(null);
        lblNomeVendedor.setText(null);
        txtCodProduto.setText(null);
        lblDescricaoProduto.setText(null);
        txtQtdeVendida.setText(null);
        lblValorTotalPed.setText(null);
        lblQtdeItensPed.setText(null);
        
        for (int i=modTblProd.getRowCount()-1; i>=0; i--) {
            modTblProd.removeRow(i);
        }
        
        txtNumPedido.setEnabled(true);
        btnConsultarPedido.setEnabled(true);
        txtDataPedido.setEnabled(false);
        rbtAVista.setEnabled(false);
        rbtAVista.setEnabled(false);
        txtCodProduto.setEnabled(false);
        btnConsultarProduto.setEnabled(false);
        txtQtdeVendida.setEnabled(false);
        btnAdicionarItem.setEnabled(false);
        btnRemoverItem.setEnabled(false);
        btnIncluir.setEnabled(false);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
    }
}
